apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofiber-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gofiber-example
  template:
    metadata:
      labels:
        app: gofiber-example
    spec:
      containers:
      - name: gofiber-example
        image: edstardo/gofiber-example
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gofiber-example
spec:
  selector:
    app: gofiber-example
  ports:
  - port: 31000
    targetPort: 3000
  type: NodePort

